### ISSUE TITLE
We show removed/banned users in follow lists

### ISSUE THREAD

**Issue by hworld** [gamejolt/next-issue-tracker#1189]

**Comment by Tricky1975** [comment]
I've received some questions about this, as people wanted to remove banned friends and banned users they follow  from their friend/follow list. Up until now I've just told them to e-mail in... Should that be the way to go until this issue has been taken care of?

**Comment by nilllzz** [comment]
Fixed.

**Comment by YLivay** [comment]
Not fixed yet, theres another unpushed part to this for feeds.

**Comment by nilllzz** [comment]
This issue is just about follow lists, if you want to include feeds, change the title.
