### ISSUE TITLE
Dismissing the content editor controls doesn't work

### ISSUE THREAD

**Issue by niksudan** [gamejolt/next-issue-tracker#1301]
When the content editor controls button is clicked, you can't accurately close it again without releasing the mouse click outside of the component.

Using Game Jolt on Firefox 67.0.3, macOS 10.14.5.

![Kapture 2019-07-04 at 11 45 52](https://user-images.githubusercontent.com/6004491/60661172-53624700-9e51-11e9-8976-448881b1e1ab.gif)

**Comment by YLivay** [comment]
Neeeeeek, do you have any extensions enabled? anything in console log?

Actually, isn't this intended behaviour? Buttons in general do that.

**Comment by nilllzz** [comment]
From the gif it looks like the editor is still focused, I wonder why that would be?

**Comment by niksudan** [comment]
Nothing in the console.

I was under the impression that clicking it again would roll it up?

**Comment by YLivay** [comment]
I think finishing the click outside the button is fine. the focus bit is weirder actually haha.
I wonder if there really are these differences between firefox on Windows and Linux..?

And yes, clicking it again should roll it up. Contentidor is doing odd mm..

**Comment by nilllzz** [comment]
Already tested it on Windows:
https://gfycat.com/tatteredevenbadger
I don't seem to get any problems doing this.

**Comment by YLivay** [comment]
If you refresh does it happen consistently?

**Comment by YLivay** [comment]
This should be fixed now but since we were never able to recreate this, can you test pls?

**Comment by niksudan** [comment]
Unfortunately seems to still occur.

I don't think this is too major anyway, as it is dismissed if you start to type or click to focus on the textarea again.

**Comment by nilllzz** [comment]
Firefox on Mac seems to have some meme problems with those buttons, not sure why.

**Comment by nilllzz** [comment]
Yeah just confirmed: It only happens on Firefox on Mac.
The main issue here is that when the + button is pressed, it doesn't unfocus the input.

**Comment by nilllzz** [comment]
We fixed this, yay
